### ISSUE TITLE
transpiled (dist) version doesn't exist on npm

### ISSUE THREAD

**Issue by mhamann** [izaakschroeder/auth-header#14]
It appears there's a `prepublish` script that should generate a `dist` folder with a transpiled (ES5) version of this module; however, in the version I just installed, nothing like that exists.

This module seems broken in that state, at least on Node v4.

**Comment by seripap** [comment]
+1

```
Error: Cannot find module 'auth-header'
```

Manually building works

**Comment by lancespeelmon** [comment]
+1 same error :frowning:

**Comment by natorojr** [comment]
+1 same error

The code looks good and I would star this project if I could get it to work with Node 4 LTS.

Would greatly appreciate a fix.

**Comment by muka** [comment]
:+1:

**Comment by lancespeelmon** [comment]
Time for `auth-header2` module? Who wants to fork and publish?

**Comment by natorojr** [comment]
@lancespeelmon,

Though I share your desire to get this fixed ASAP, I'm not sure I agree that forking the project is necessary to do so.

IMHO, one of the major problems that plagues social-coding/open-source today is this tendency towards forking projects for the sake of making one-off fixes with no intention of merging back into the original source. This, in turns, amplifies yet another major problem that plagues social-coding/open-source today, which is the over-abundance and -saturation of projects that do essentially the same thing, which makes our lives as open-source consumers difficult in that it introduces the time-consuming process of having to evaluate and choose from a plethora of libraries with seemingly identical purpose.

Dear @izaakschroeder,

Is your delay in addressing this issue merely one of lacking the time to do so? Or, have you decided, for whatever reason, not to maintain this project moving forward? In the case of the former, would you consider adding collaborators/members to the project to assist in the day-to-day maintenance of the project? In the case of the later, would you consider transferring stewardship of the project altogether?

In either case, I'm happy to volunteer my services. Given the specificity of the project's purpose and a relatively small code base, I would be surprised if it took more than an hour of my week to keep things in shape.

At the moment, I believe the problem here is that you do not have a `.npmignore` file. In the absence of a `.npmignore` file, `npm publish` will simply fall back on `.gitignore`, which currently excludes your `dist/` folder (as it should). Alternatively, you could use a `files` entry in your package.json: https://docs.npmjs.com/files/package.json#files

That said, it seems like @aliatsis has already submitted a PR that should fix this problem https://github.com/izaakschroeder/auth-header/pull/15

**Comment by izaakschroeder** [comment]
Ack sorry it's taken so long! Will get to this today 😄 Not inactive, rather the opposite. I need to figure out a better way to deal with GH notifications (or currently lack thereof) mainly due to having so many to sift through. Separating signal from noise is something I need to figure out. Thanks for bringing this up!

**Comment by izaakschroeder** [comment]
https://github.com/izaakschroeder/auth-header/pull/15 is merged and new version is published as `0.3.1`.

**Comment by izaakschroeder** [comment]
<img width="760" alt="screen shot 2016-04-22 at 10 44 42 am" src="https://cloud.githubusercontent.com/assets/206921/14749968/445d0e66-0877-11e6-8756-0d4371da38ea.png">

Looks ok from here!

**Comment by izaakschroeder** [comment]
Also as an aside, happy to a) add others as maintainers and b) move this project to an organization that would maybe make life easier. Apologies again for the huge delay, not intentional on my part 😭

**Comment by lancespeelmon** [comment]
Thank you!!!!

**Comment by natorojr** [comment]
Thanks, @izaakschroeder. It's working in both my development and production builds!

No worries on the delay, glad that my last message got through.

My offer stands, let me know if you want to add me as a maintainer so you can distribute the responsibility of maintenance. I've got 20 years of software development experience (over half of that w/ JavaScript), so, at minimum, I should be able to help you address some of the low-hanging fruit that comes up like this one.

**Comment by izaakschroeder** [comment]
Added @natorojr thanks! Updated my notification settings again hopefully I've reached some kind of happy middle ground... @-mention directly if anything else comes up 😄
