### ISSUE TITLE
Lighten lib by removing lodash

### ISSUE THREAD

**Issue by knownasilya** [izaakschroeder/auth-header#5]
Seems like this lib should be pretty light, but the use of lodash really makes it unnecessarily bulky.

**Comment by izaakschroeder** [comment]
There are some features that lo-dash has that are very convenient, in particular the `_.find` function (and soon the `_.isMatch` function when v3.0.0 lands). I admit that I could use less of lo-dash by simply requiring the modules for each associated function (e.g. `require('lodash/find')` instead of the full `require('lodash')`.

The only problem with your PR using native is that you will also have to provide an implementation of `_.find` which, using where-style matching, is probably non-trivial.

Thoughts?

**Comment by knownasilya** [comment]
@izaakschroeder I agree, and requiring only the methods that you use would be a good alternative.

Why would `_.find` have anything to do with map/filter, which are native? `_.find` will still work perfectly fine, if you replace don't use `_.map`/`_.filter`.

**Comment by izaakschroeder** [comment]
> Why would `_.find` have anything to do with `map`/`filter`, which are native? `_.find` will still work perfectly fine, if you replace [...] `_.map`/`_.filter`.

Yes! This is true. I feel like it's better to be consistent and performant in this case though; as heavy as lo-dash is, it still actually outperforms native: http://jsperf.com/native-for-loop-vs-array-foreach-and-array-map-vs-lodas.

With that in mind I think the best solution going forward is to use individual function modules (e.g. `require('lodash/foo')` as opposed to entire lo-dash, but I don't think throwing lo-dash out is going to be on the table, including `_.map` and `_.filter`.

**Comment by knownasilya** [comment]
I'm fine with that, since it's your call :smile:

**Comment by izaakschroeder** [comment]
It's been a long time :smile: but `lodash` is no more! https://github.com/izaakschroeder/auth-header/pull/13

**Comment by knownasilya** [comment]
Nice!
